### ISSUE TITLE
Call to undefined function geoip_db_avail()

### ISSUE THREAD

**Issue by elkrari** [rmrevin/yii2-geoip#2]
I got the error "Call to undefined function rmrevin\yii\geoip\geoip_db_avail()". I can't found this package in rmrevin package generated by composer

**Comment by rmrevin** [comment]
Probably you have not installed the extension php geoip.

**Comment by elkrari** [comment]
Yeah, cause i got errors while installing (php 5.4 under Ubuntu 12.04 LTS) . I thought your extension contains all components. 
I'll try to installing it.
Thanks :-)
