### ISSUE TITLE
Can I use this extension along with locale urls ?

### ISSUE THREAD

**Issue by offline-online** [rmrevin/yii2-geoip#4]
So if user from France come ti visit my site I would like to load fr language. If user from UK comes to my site I would like to load en-uk language. Your extension is recognizing geo ip, but is it possible to combine your extension with this one https://github.com/codemix/yii2-localeurls ? I am already using this extension in my website and it is amazing, but now I need to be able to detect location of the user and load language based on that. Is it possible ? Thanks for your great work !

EDIT: so when user comes to my site for the first time, I want to load language based on his location, but he should still be able to chose other languages that app is offering to him via locale urls.

**Comment by rmrevin** [comment]
Good afternoon.
Unfortunately, we do not support third-party plug-ins.
In this case, you will need to extend the functionality of the plugin yii2-localeurls.
You can contact the authors of the plugin.
