### ISSUE TITLE
rmrevin\yii\geoip\geoip_db_avail()

### ISSUE THREAD

**Issue by Davit21** [rmrevin/yii2-geoip#5]
Hi,I am use yii2 and im install yii2-geoip via composer 
like this  "rmrevin/yii2-geoip": "1.0.4" 
but when i am try use  this example  $Info = \Yii::createObject([
            'class' => '\rmrevin\yii\geoip\HostInfo',
            'host' => 'phptime.ru', // some host or ip
        ]); it's throws exception\
Call to undefined function rmrevin\yii\geoip\geoip_db_avail()

Thanks beforehand.

**Comment by rmrevin** [comment]
You need to install the extension [php5-geoip](http://php.net/geoip)
