### ISSUE TITLE
 I am unable to get the answer

### ISSUE THREAD

**Issue by rafaelvaloto** [rmrevin/yii2-geoip#6]
I am unable to get the answer.

the setting is correct ?

```
$Info = \Yii::createObject([
         'class' => '\rmrevin\yii\geoip\HostInfo',
         'host' => \Yii::$app->getRequest()->getUserIP(), // some host or ip
]);
echo '<pre>';
var_dump($Info->isAvailable()); 
var_dump($Info->getData()); 

return
bool(false)
NULL
```

**Comment by rmrevin** [comment]
@rafaelvaloto Hi. Install library php5-geoip

**Comment by rafaelvaloto** [comment]
@rmrevin Hi, php5-geoip is already the newest version

**Comment by rmrevin** [comment]
What returns `var_dump(\Yii::$app->getRequest()->getUserIP())`

**Comment by rafaelvaloto** [comment]
return My IP 191.177.XXX.XX

```
var_dump($Info);

object(rmrevin\yii\geoip\HostInfo)#86 (4) {
  ["host"]=>
  string(14) "191.177.XXX.XX"
  ["data":"rmrevin\yii\geoip\HostInfo":private]=>
  bool(false)
  ["_events":"yii\base\Component":private]=>
  array(0) {
  }
  ["_behaviors":"yii\base\Component":private]=>
  NULL
}
```

**Comment by rmrevin** [comment]
Check the error log, maybe there is an error
![](http://i.imgur.com/paU1IZ8.png)

**Comment by rafaelvaloto** [comment]
yes , how can I solve this? Tanks

**Comment by rmrevin** [comment]
Download this file http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz and ungzip it into /usr/share/GeoIP/GeoIPCity.dat

**Comment by rafaelvaloto** [comment]
Thank you very much.

**Comment by rmrevin** [comment]
I'm glad I could help.
It's annoying that some linux systems do not have this database.
