### ISSUE TITLE
Page with .dat not found

### ISSUE THREAD

**Issue by luckyalexandr** [rmrevin/yii2-geoip#7]
This path `http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz` not working
Where i can change path to GeoIPCity.dat?

**Comment by rmrevin** [comment]
Maxmind dropped this file https://support.maxmind.com/geolite-legacy-discontinuation-notice/ . Current package is now deprecated. Use official package https://packagist.org/packages/geoip2/geoip2
